global:
  netop_docker_existingImagePullSecret: "kubeslice-image-pull-secret"
  # IF You dont have existing secret then pass all below values it will create new secret "avesha-docker-ips"
  ## MANDOTORY FIELDS IF EXISTING SECRET NOT PRESENT ##
  netop_docker_imagePullSecrets:
    repository:
    username: ''
    password: ''
    email: ''
  imageRegistry: ghcr.io/kube-slice
netop:
  networkInterface: eth0
  image: netops
  tag: v0.3.0-ac
  pullPolicy: IfNotPresent
