---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsc-grpc-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsc-grpc-server-pod-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nsc-grpc-server-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: nsc-grpc-server
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nsc-grpc-server-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nsc-grpc-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: nsc-grpc-server
  template:
    metadata:
      labels:
        app: nsc-grpc-server
    spec:
      serviceAccountName: nsc-grpc-server
      containers:
        - name: nsc-grpc-server
          image: "{{ .Values.global.imageRegistry }}/{{.Values.nscgrpc.cmdnscgrpcServerImageRegistry}}:{{.Values.nscgrpc.cmdnscgrpcServerImageTag}}"
          imagePullPolicy: Always
          env:
            - name: NSM_CONNECT_TO
              value: tcp://nsmgr.kubeslice-system.svc:5001
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_LIVENESSCHECKENABLED
              value: "false"
            - name: NSM_REQUEST_TIMEOUT
              value: 60s
            - name: NSM_INITLOCALDNSCONFIG
              value: "false"
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: kernel://vl3-service-slice/nsm0
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 50052
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            privileged: {{ eq "true" ( include "distro.openshift" . ) }}
            capabilities:
              add:
                - NET_BIND_SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: nsc-grpc-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nsc-grpc-server
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: nsc
