---
# Default values for admission-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nsmw_docker_existingImagePullSecret: "kubeslice-image-pull-secret"
  # IF You dont have existing secret then pass all below values it will create new secret "avesha-docker-ips"
  ## MANDOTORY FIELDS IF EXISTING SECRET NOT PRESENT ##
  nsmw_docker_imagePullSecrets:
    repository:
    username: ''
    password: ''
    email: ''
  imageRegistry: ghcr.io/kube-slice

webhookImageRegistry: cmd-admission-webhook-k8s
webhookImageTag: v1.7.3

nsmInjectContainerImageRegistry: cmd-nsc
nsmInjectContainerImageTag: v1.5.12

nsmInjectInitContainerImageRegistry: cmd-nsc-init
nsmInjectInitContainerImageTag: v1.5.8
nsmInitContainerUpdateDNSConfig: true

# nsm admission webhook ns
nsmNs: kubeslice-nsm-webhook-system

apiserver:
  servingCerts:
    generate: true
    caCrt: ""
    serverCrt: ""
    serverKey: ""
