---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: spire
data:
  bundle.crt: |
{{- if .Values.apiserver.bundleCrt }}
{{ .Values.apiserver.bundleCrt | b64dec | indent 4 }}
{{- end }}