---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: spire
{{- if .Values.apiserver.bundleCrt }}
data:
  bundle.crt: |
{{ .Values.apiserver.bundleCrt | b64dec | indent 4 }}
{{- end }}